name: gen_fingerprints

on: [push]

jobs:
  gen_fingerprints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Generate fingerprints.json
        run: python3 scripts/gen_fingerprints.py > fingerprints.json
      - name: prettier
        uses: actions/setup-node@v3
      - run: npm install --save-dev --save-exact prettier
      - run: npx prettier --write .
      - name: git commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "prettier + refresh fingerprints.json"
